## List

In [50]:
list_1 = [3, 19, 112, 4731]
list_1

[3, 19, 112, 4731]

In [2]:
type(list_1)

list

In [3]:
len(list_1)

4

In [51]:
list_2 = ['b', '7', 'b7']
list_2

['b', '7', 'b7']

In [52]:
list_3 = [3, 19, 112, 4731, '37,5'] 
list_3

[3, 19, 112, 4731, '37,5']

In [6]:
list_all = list_1 + list_2 + list_3
list_all

[3, 19, 112, 4731, 'b', '7', 'b7', 3, 19, 112, 4731, '37,5']

In [7]:
list_all[1:3]

[19, 112]

In [8]:
list_all[0] = '3'
list_all

['3', 19, 112, 4731, 'b', '7', 'b7', 3, 19, 112, 4731, '37,5']

In [9]:
'b' in list_all

True

In [10]:
list_2.append('b') 
list_2

['b', '7', 'b7', 'b']

In [11]:
list_1.insert(1,8)
list_1

[3, 8, 19, 112, 4731]

In [12]:
list_2.count('b')

2

In [13]:
list_3.pop(4)  
list_3 

[3, 19, 112, 4731]

In [14]:
list_2.remove('b')   
list_2 

['7', 'b7', 'b']

In [15]:
list_1.sort()
list_1

[3, 8, 19, 112, 4731]

In [16]:
list_1.sort(reverse=True)
list_1

[4731, 112, 19, 8, 3]

In [17]:
list_2.sort()
list_1

[4731, 112, 19, 8, 3]

In [18]:
list_4 = ['X',1.5,[2,3,4]]
list_4

['X', 1.5, [2, 3, 4]]

## Tuple

In [19]:
tuple_1 = ('X',1.5,[2,3,4])
tuple_1

('X', 1.5, [2, 3, 4])

In [217]:
type(tuple_1)

tuple

In [20]:
#tuple_1[0] = 'Y'

In [21]:
list_5 = list(tuple_1)
list_5

['X', 1.5, [2, 3, 4]]

In [22]:
list_5[0] = 'Y'
list_5

['Y', 1.5, [2, 3, 4]]

## Dictionary

In [23]:
dict_1 = {'key1':'value1','key2':'value2'} 
dict_1

{'key1': 'value1', 'key2': 'value2'}

In [218]:
type(dict_1)

dict

In [24]:
dict_1['key1']

'value1'

In [25]:
dict_2 = {'maşın':'Kia','model':'Sportage','il':2015,'rəng':'ağ'}
dict_2

{'maşın': 'Kia', 'model': 'Sportage', 'il': 2015, 'rəng': 'ağ'}

In [26]:
dict_2['model']

'Sportage'

In [27]:
dict_2.items()

dict_items([('maşın', 'Kia'), ('model', 'Sportage'), ('il', 2015), ('rəng', 'ağ')])

In [28]:
dict_2.keys()

dict_keys(['maşın', 'model', 'il', 'rəng'])

In [29]:
dict_2.values()

dict_values(['Kia', 'Sportage', 2015, 'ağ'])

In [30]:
dict_2['km'] = 125000
dict_2

{'maşın': 'Kia', 'model': 'Sportage', 'il': 2015, 'rəng': 'ağ', 'km': 125000}

In [31]:
km = {'km':'125500'}
km

{'km': '125500'}

In [32]:
dict_2.update(km)
dict_2

{'maşın': 'Kia', 'model': 'Sportage', 'il': 2015, 'rəng': 'ağ', 'km': '125500'}

In [33]:
dict_2.pop('il')
dict_2

{'maşın': 'Kia', 'model': 'Sportage', 'rəng': 'ağ', 'km': '125500'}

In [34]:
dict_3 = {'k1':9,'k2':list_1,'k3':km}
dict_3

{'k1': 9, 'k2': [4731, 112, 19, 8, 3], 'k3': {'km': '125500'}}

In [35]:
dict_3['k3']['km']

'125500'

In [36]:
dict_3['k2'][2]

19

## Array

In [37]:
import numpy as np

In [38]:
array_1 = np.array(list_1)
array_1

array([4731,  112,   19,    8,    3])

In [219]:
type(array_1)

numpy.ndarray

In [55]:
list_1 = [1,2,3]
list_2 = [4,5,6]
list_3 = [7,8,9]

In [56]:
list_comb = [list_1,list_2,list_3]
list_comb

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [65]:
array_2 = np.array(list_comb)
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
array_2.dtype

dtype('int64')

In [68]:
array_3 = np.array(array_2, dtype='float')
array_3

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [74]:
array_4 = array_3.astype('int')
print(array_4)
print(array_4.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64


In [107]:
array_4.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [75]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [77]:
np.arange(5,19,2)

array([ 5,  7,  9, 11, 13, 15, 17])

In [86]:
np.linspace(0,9,5)

array([0.  , 2.25, 4.5 , 6.75, 9.  ])

In [89]:
import numpy.random as rd
rd.rand(10)

array([0.21442864, 0.22376244, 0.46163365, 0.83452629, 0.48741885,
       0.17644723, 0.93736942, 0.86704722, 0.64338301, 0.20187959])

In [111]:
array_5 = rd.randint(2,5,10)
array_5

array([4, 4, 3, 2, 3, 2, 3, 3, 4, 2])

In [110]:
rd.randn(10) #normal distribution

array([-2.16586536e+00, -1.03431787e+00, -6.07874547e-01, -1.99370333e-03,
       -1.68383958e-01, -5.03312445e-01, -5.64270782e-01,  4.51614334e-01,
        7.68323913e-01,  9.25589341e-02])

In [146]:
array_6 = np.random.randint(0,19,10)
array_6

array([12, 13,  7,  7, 16,  5, 12, 16,  9,  7])

In [113]:
array_5 + array_6

array([16,  8,  3, 20,  3, 16,  5,  6, 14, 18])

In [116]:
array_5 + array_6

array([16,  8,  3, 20,  3, 16,  5,  6, 14, 18])

In [117]:
array_5 * array_6

array([48, 16,  0, 36,  0, 28,  6,  9, 40, 32])

In [119]:
array_5 * 10

array([40, 40, 30, 20, 30, 20, 30, 30, 40, 20])

In [122]:
10 / array_5 

array([2.5       , 2.5       , 3.33333333, 5.        , 3.33333333,
       5.        , 3.33333333, 3.33333333, 2.5       , 5.        ])

In [125]:
10 // array_5 

array([2, 2, 3, 5, 3, 5, 3, 3, 2, 5])

In [126]:
array_5 / array_6

/var/folders/w5/0qbzsvvx23g_63j6m77_09nm0000gn/T/ipykernel_24020/504191720.py:1: RuntimeWarning: divide by zero encountered in divide
  array_5 / array_6


array([0.33333333, 1.        ,        inf, 0.11111111,        inf,
       0.14285714, 1.5       , 1.        , 0.4       , 0.125     ])

In [130]:
array_6[3:6]

array([18,  0, 14])

In [134]:
array_6[4:-1]

array([ 0, 14,  2,  3, 10])

In [135]:
array_6[4:-1:2]

array([ 0,  2, 10])

In [138]:
array_6[3::2]

array([18, 14,  3, 16])

In [141]:
array_5[0:4] = 0
array_5

array([0, 0, 0, 0, 3, 2, 3, 3, 4, 2])

In [152]:
array_5b = array_5[4:]
array_5b

array([3, 2, 3, 3, 4, 2])

In [153]:
array_5b[:] = 0
array_5b

array([0, 0, 0, 0, 0, 0])

In [154]:
array_5

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [155]:
array_5b_copy = array_5[4:].copy()
array_5b_copy

array([0, 0, 0, 0, 0, 0])

In [206]:
array_5b_copy[:] = 9
print(array_5b_copy)
print(array_5)

[9 9 9 9 9 9]
[0 0 0 0 0 0 0 0 0 0]


In [207]:
np.unique(array_5)

array([0])

### 2D array

In [168]:
array_7 = np.array((np.arange(3),np.arange(3,6),np.arange(6,9)))
array_7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [212]:
array_7.size

9

In [213]:
array_7.shape

(3, 3)

In [169]:
array_7[0]

array([0, 1, 2])

In [170]:
array_7[0][0]

0

In [173]:
array_7[0,1]

1

In [178]:
array_7[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [179]:
array_7[0:1,1:]

array([[1, 2]])

In [180]:
array_8 = np.arange(24).reshape(6,4)
array_8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [184]:
array_8[[0,2],:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [185]:
array_8 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [188]:
array_9 = array_8 > 10
array_8[array_9]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [191]:
array_8.sum()

276

In [193]:
array_8.sum(axis = 0)

array([60, 66, 72, 78])

In [194]:
array_8.sum(axis = 1)

array([ 6, 22, 38, 54, 70, 86])

In [196]:
array_8.max(axis = 0)

array([20, 21, 22, 23])

In [199]:
array_8.min(axis = 1)

array([ 0,  4,  8, 12, 16, 20])

In [203]:
array_8.sort(axis=0)
array_8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [204]:
array_8.sort(axis=1)
array_8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [214]:
array_9 = np.array([True,True,False,False])
array_9

array([ True,  True, False, False])

In [215]:
array_9.any()

True

In [216]:
array_9.all()

False