# Matris Əməliyyatları və Determinant (Praktikum II)

Bu notebook NumPy-da genişlənmiş matrislərarası əməliyyatları (Broadcasting, Trace, Vurma fərqləri) və determinatı əhatə edir.

## 1. Element-bə-element əməliyyatlar vs Matris Hasil

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("A:\n", A)
print("B:\n", B)

In [7]:
# Hadamard Vurması (element-elementə)
hadamard = A * B
print("Hadamard Hasil (A * B):\n", hadamard)

# Matris Hasil (Dot product)
dot_prod = A @ B  # və ya np.dot(A, B)
print("\nMatrisin Riyazi Hasili (A @ B):\n", dot_prod)

A:
 [[1 2]
 [3 4]]
B:
 [[2 0]
 [1 2]]


**Kommutativlik Testi:** $AB \neq BA$

In [8]:
print("A @ B:\n", A @ B)
print("\nB @ A:\n", B @ A)
print("\nGördüyünüz kimi fərqli nəticələr alındı!")

Hadamard Hasil (A * B):
 [[2 0]
 [3 8]]

Matrisin Riyazi Hasili (A @ B):
 [[ 4  4]
 [10  8]]


In [29]:
# Matrisin Riyazi Hasili (A @ B)
np.array([
    [A[0,0] * B[0,0], A[0,1] * B[0,1]],
    [A[1,0] * B[1,0], A[1,1] * B[1,1]]
])

array([[2, 0],
       [3, 8]])

In [30]:
# Hadamard Hasil (A * B)
np.array([
    [A[0,0] * B[0,0] + A[0,1] * B[1,0], A[0,0] * B[0,1] + A[0,1] * B[1,1]],
    [A[1,0] * B[0,0] + A[1,1] * B[1,0], A[1,0] * B[0,1] + A[1,1] * B[1,1]]
])

array([[ 4,  4],
       [10,  8]])

## 2. Broadcasting (Yayılma) Xüsusiyyəti

NumPy-da müxtəlif ölçülü array-ləri (məsələn vektorla matrisi) toplamaq olur. Numpy vektoru avtomatik olaraq təkrar edib (yayaraq) ölçüləri uyğunlaşdırır.

In [39]:
Matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
Vec = np.array([10, 20, 30])

# Matrix (3x3) + Vektor (1x3)
print("Matrix + Vektor (Broadcasting):\n", Matrix + Vec)

Matrix + Vektor (Broadcasting):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


## 3. Matrisin İzi (Trace) və Determinant

### 3.1 Matrisin İzi (Trace)
Kvadrat matrisin **izi** ($Tr(A)$), onun əsas diaqonalı üzərində yerləşən elementlərin cəminə bərabərdir.

**Əsas xassələr:**
1. **Xəttilik:** $Tr(A+B) = Tr(A) + Tr(B)$
2. **Siklik xassə:** $Tr(AB) = Tr(BA)$ (Baxmayaraq ki, $AB \neq BA$)

In [44]:
# İzi (Trace) hesablamaq
M1 = np.array([[5, 2, 1], 
               [0, -3, 8], 
               [4, 1, 7]])

print("M1 matrisinin İzi:", np.trace(M1)) 

M1 matrisinin İzi: 9


In [ ]:
M1[0,0] + M1[1,1] + M1[2,2]

np.int64(9)

In [46]:
# Dövri xassənin yoxlanılması
M2 = np.array([[1, 0, 2], 
               [3, 4, 5], 
               [0, 2, 1]])

tr_AB = np.trace(M1 @ M2)
tr_BA = np.trace(M2 @ M1)

print(f"\nTr(M1 @ M2) = {tr_AB}")
print(f"Tr(M2 @ M1) = {tr_BA}")
print("Xassə doğrudurmu?", tr_AB == tr_BA)


Tr(M1 @ M2) = 35
Tr(M2 @ M1) = 35
Xassə doğrudurmu? True


### 3.2 Determinant və Onun Xassələri

Determinant fəzanın ölçü dəyişmə faktorudur. 

**Vacib Xassələr:**
1. $\det(AB) = \det(A) \cdot \det(B)$
2. $\det(kA) = k^n \det(A)$ (burada $n$ matrisin ölçüsüdür)
3. $\det(A^T) = \det(A)$

In [53]:
# 1. 2x2 Determinant: det([[3,4],[2,5]]) = 15 - 8 = 7
A_2x2 = np.array([[3, 4], 
                  [2, 5]])
print("2x2 Determinant:", np.linalg.det(A_2x2))

# 2. 3x3 Determinant
B_3x3 = np.array([[1, 2, 3], 
                  [0, 1, 4], 
                  [5, 6, 0]])
print("3x3 Determinant:", round(np.linalg.det(B_3x3), 2))

# 3. Xassə yoxlanışı: det(2A) = 2^2 * det(A) = 4 * 7 = 28
k = 2
det_kA = np.linalg.det(k * A_2x2)
print(f"\ndet(2 * A_2x2) = {round(det_kA, 2)}")

2x2 Determinant: 7.000000000000001
3x3 Determinant: 1.0

det(2 * A_2x2) = 28.0


## 4. Tətbiq: Cramer Qaydası

Aşağıdakı sistemi Cramer qaydası ilə həll edək:

$2x + 3y = 8$

$x - y = -1$

In [54]:
C = np.array([[2, 3], 
              [1, -1]])
R = np.array([8, -1])

det_C = np.linalg.det(C)

det_C

np.float64(-5.000000000000001)

In [55]:
# x-i tapmaq üçün x sütununu dəyişdik
Cx = np.column_stack([R, C[:, 1]])
Cx

array([[ 8,  3],
       [-1, -1]])

In [63]:
det_Cx = np.linalg.det(Cx)
x = det_Cx / det_C

# y-i tapmaq üçün y sütununu dəyişdik
Cy = np.column_stack([C[:, 0], R])
det_Cy = np.linalg.det(Cy)
y = det_Cy / det_C

print(f"X = {round(x, 2)}, Y = {round(y, 2)}")

X = 1.0, Y = 2.0
