# Tərs, Transpoz və Tənliklər Sistemi (Praktikum III)

Bu notebook-da transpoz, matris tərsi, simmetrik matrisin konseptini və $Ax=B$ tipli tənliklər sisteminin həllini yazacağıq.

In [1]:
import numpy as np

## 1. Transpoz və Simmetrik Matrisin Yoxlanılması

In [2]:
S = np.array([[1, 7, 3],
              [7, 4, 5],
              [3, 5, 2]])

# Simmetrik olduğunu yoxlamaq (S = S^T olmalıdır)
S_T = S.T

print("S matrisi:\n", S)
print("\nS Transpozu:\n", S_T)

# NumPy-da 'np.array_equal' və ya 'np.allclose' ilə iki matrisin bərabərliyi test edilir
is_symmetric = np.allclose(S, S_T)
print("\nMatris simmetrikdirmi?", is_symmetric)

S matrisi:
 [[1 7 3]
 [7 4 5]
 [3 5 2]]

S Transpozu:
 [[1 7 3]
 [7 4 5]
 [3 5 2]]

Matris simmetrikdirmi? True


## 2. Matrisin Tərsi və Çökmüş Matris Məsələsi (Singular Matrix)

In [4]:
# Analitik Misal (MD faylındakı): A = [[1, 2], [3, 4]]
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print("A matrisinin tərsi:\n", A_inv)

# Yoxlama: A * A_inv = I
I_check = A @ A_inv
print("\nYoxlama (A @ A_inv):\n", np.round(I_check, 2))

A matrisinin tərsi:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Yoxlama (A @ A_inv):
 [[1. 0.]
 [0. 1.]]


In [5]:
# Singular (tərsi olmayan) matris formalaşdıraq -- Asılı sətirlər olmalıdır.
Singular = np.array([[1, 2],
                     [2, 4]])  # 2-ci sətir 1-cinin 2 qatıdır.
                     
print("\nSingular matrisin determinantı:", np.linalg.det(Singular))

try:
    inv_Singular = np.linalg.inv(Singular)
except np.linalg.LinAlgError as e:
    print("\nXƏTA YARANDI:", e)  # Singular matrix xətası atacaq


Singular matrisin determinantı: 0.0

XƏTA YARANDI: Singular matrix


## 3. Xətti Tənliklər Sisteminin Həlli ($Ax=b$)

### Misal: Sistem tənliyin matris üsulu ilə həlli
Aşağıdakı tənliklər sistemini həll edək:
1. $2x + y = 5$
2. $3x + 2y = 8$

Bunu matris formatında yazırıq: 
$A = \begin{bmatrix} 2 & 1 \\ 3 & 2 \end{bmatrix}$, $\mathbf{x} = \begin{bmatrix} x \\ y \end{bmatrix}$, $\mathbf{b} = \begin{bmatrix} 5 \\ 8 \end{bmatrix}$

In [14]:
A_sys = np.array([[2, 1],
                  [3, 2]])
b_sys = np.array([5, 8])

np.linalg.inv(A_sys)


array([[ 2., -1.],
       [-3.,  2.]])

In [13]:
# 1-ci yanaşma: A^-1 * b düsturu (Riyazi yanaşma)
x_approach1 = np.linalg.inv(A_sys) @ b_sys
print("1-ci Yanaşma (A_inv @ b) cavab:", x_approach1)

1-ci Yanaşma (A_inv @ b) cavab: [2. 1.]


In [15]:
# 2-ci yanaşma: np.linalg.solve (Daha sürətli və stabil)
x_approach2 = np.linalg.solve(A_sys, b_sys)
print("2-ci Yanaşma (np.linalg.solve) cavab:", x_approach2)

2-ci Yanaşma (np.linalg.solve) cavab: [2. 1.]
