## Vector 2

In [1]:
vec_1 <- c(3, 19, 112, 4731)
names(vec_1)

NULL

In [2]:
names(vec_1) <- 1:4
vec_1

1    2    3    4 
   3   19  112 4731

In [3]:
vec_2 <- vec_1
names(vec_2) <- c("A", "B", "C", "D")
vec_2

A    B    C    D 
   3   19  112 4731

In [4]:
vec_2[1]
vec_2["A"]

A 
3

A 
3

In [5]:
vec_2[c("A", "D")]

A    D 
   3 4731

In [6]:
vec_2 > 19

A     B     C     D 
FALSE FALSE  TRUE  TRUE

In [7]:
vec_2[vec_2 > 19]

C    D 
 112 4731

In [8]:
vec_1[vec_1 > 19] <- vec_1[vec_1 > 19] / 2
vec_1

1      2      3      4 
   3.0   19.0   56.0 2365.5

In [9]:
vec_1 + vec_2
vec_2 + vec_1

1      2      3      4 
   6.0   38.0  168.0 7096.5

A      B      C      D 
   6.0   38.0  168.0 7096.5

In [10]:
vec_3 <- vec_1
names(vec_3) <- c("Z", "B", "C", "F")
vec_3

Z      B      C      F 
   3.0   19.0   56.0 2365.5

In [11]:
vec_4 <- vec_2 + vec_3 
vec_4

A      B      C      D 
   6.0   38.0  168.0 7096.5

In [12]:
vec_3[c("B","C","F","Z")]

B      C      F      Z 
  19.0   56.0 2365.5    3.0

In [13]:
vec_3[sort(names(vec_3))]

B      C      F      Z 
  19.0   56.0 2365.5    3.0

In [14]:
vec_3[sort(names(vec_3), decreasing = T)]

Z      F      C      B 
   3.0 2365.5   56.0   19.0

In [15]:
vec_3[names(vec_3) != "Z"]

B      C      F 
  19.0   56.0 2365.5

In [16]:
vec_3[names(vec_3) != c("C", "F")]
vec_3[!names(vec_3) %in% c("C", "F")]

Z  B 
 3 19

Z  B 
 3 19

In [17]:
vec_1 <- c(vec_1, 3, 19)

In [18]:
names(vec_1)[5:6] <- 5:6
names(vec_1)

[1] "1" "2" "3" "4" "5" "6"

In [19]:
vec_1
vec_2
vec_3

1      2      3      4      5      6 
   3.0   19.0   56.0 2365.5    3.0   19.0

A    B    C    D 
   3   19  112 4731

Z      B      C      F 
   3.0   19.0   56.0 2365.5

In [20]:
rbind(vec_1, vec_1)

1 2  3  4      5 6 
vec_1 3 19 56 2365.5 3 19
vec_1 3 19 56 2365.5 3 19

In [21]:
cbind(vec_1, vec_1)

vec_1  vec_1 
1    3.0    3.0
2   19.0   19.0
3   56.0   56.0
4 2365.5 2365.5
5    3.0    3.0
6   19.0   19.0

In [22]:
rbind(vec_1, vec_2)
rbind(vec_2, vec_1)

Warning message in rbind(vec_1, vec_2):
“number of columns of result is not a multiple of vector length (arg 2)”


1 2  3   4      5 6 
vec_1 3 19  56 2365.5 3 19
vec_2 3 19 112 4731.0 3 19

Warning message in rbind(vec_2, vec_1):
“number of columns of result is not a multiple of vector length (arg 1)”


1 2  3   4      5 6 
vec_2 3 19 112 4731.0 3 19
vec_1 3 19  56 2365.5 3 19

In [23]:
rbind(vec_1, vec_2)
rbind(vec_2, vec_1)

Warning message in rbind(vec_1, vec_2):
“number of columns of result is not a multiple of vector length (arg 2)”


1 2  3   4      5 6 
vec_1 3 19  56 2365.5 3 19
vec_2 3 19 112 4731.0 3 19

Warning message in rbind(vec_2, vec_1):
“number of columns of result is not a multiple of vector length (arg 1)”


1 2  3   4      5 6 
vec_2 3 19 112 4731.0 3 19
vec_1 3 19  56 2365.5 3 19

In [24]:
cbind(vec_1, vec_3)
cbind(vec_3, vec_1)

Warning message in cbind(vec_1, vec_3):
“number of rows of result is not a multiple of vector length (arg 2)”


vec_1  vec_3 
1    3.0    3.0
2   19.0   19.0
3   56.0   56.0
4 2365.5 2365.5
5    3.0    3.0
6   19.0   19.0

Warning message in cbind(vec_3, vec_1):
“number of rows of result is not a multiple of vector length (arg 1)”


vec_3  vec_1 
1    3.0    3.0
2   19.0   19.0
3   56.0   56.0
4 2365.5 2365.5
5    3.0    3.0
6   19.0   19.0

## Matrix

In [25]:
matrix_1 <- matrix(data = 1:9, ncol = 3, nrow = 3)
matrix_1

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [26]:
matrix_2 <- matrix(data = 1:9, ncol = 3, nrow = 3, byrow = TRUE)
matrix_2

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [27]:
matrix_3 <- cbind(matrix_1,matrix_2)
matrix_3

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    4    7    1    2    3   
[2,] 2    5    8    4    5    6   
[3,] 3    6    9    7    8    9

In [28]:
matrix_4 <- rbind(matrix_1,matrix_2)
matrix_4

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9   
[4,] 1    2    3   
[5,] 4    5    6   
[6,] 7    8    9

In [29]:
matrix_3[2,3]

[1] 8

In [30]:
matrix_3[2,]

[1] 2 5 8 4 5 6

In [31]:
matrix_3[,3]

[1] 7 8 9

In [32]:
matrix_3

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    4    7    1    2    3   
[2,] 2    5    8    4    5    6   
[3,] 3    6    9    7    8    9

In [33]:
matrix_3[2:3,c(1,6)]

[,1] [,2]
[1,] 2    6   
[2,] 3    9

## DataFrame

In [34]:
df_1 <- as.data.frame(matrix_4)
df_1

V1 V2 V3
1 1  4  7 
2 2  5  8 
3 3  6  9 
4 1  2  3 
5 4  5  6 
6 7  8  9

In [35]:
df_1[2,3]

[1] 8

In [36]:
df_1[2,]

V1 V2 V3
2 2  5  8

In [37]:
df_1[,3]

[1] 7 8 9 3 6 9

In [38]:
df_1[2:3,c(1,3)]

V1 V3
2 2  8 
3 3  9

In [39]:
df_1[2]

V2
1 4 
2 5 
3 6 
4 2 
5 5 
6 8

In [40]:
df_1[[2]]
df_1[,2]

[1] 4 5 6 2 5 8

[1] 4 5 6 2 5 8

In [41]:
df_1$V2
df_1[["V2"]]
df_1[,"V2"]

[1] 4 5 6 2 5 8

[1] 4 5 6 2 5 8

[1] 4 5 6 2 5 8

In [42]:
df_1[2:5,"V2"]
df_1[2:5,]$V2
df_1$V2[2:5]

[1] 5 6 2 5

[1] 5 6 2 5

[1] 5 6 2 5

In [43]:
matrix_3 <- matrix(0:23, nrow=6, ncol=4, byrow=TRUE)
df_2 <- as.data.frame(matrix_3)

rownames(df_2) <- c("r1", "r2", "r3", "r4", "r5", "r6")
colnames(df_2) <- c("c1", "c2", "c3", "c4")

df_2

c1 c2 c3 c4
r1  0  1  2  3
r2  4  5  6  7
r3  8  9 10 11
r4 12 13 14 15
r5 16 17 18 19
r6 20 21 22 23

In [44]:
rownames(df_2)
colnames(df_2)

[1] "r1" "r2" "r3" "r4" "r5" "r6"

[1] "c1" "c2" "c3" "c4"

In [45]:
df_2 > 6

c1    c2    c3    c4   
r1 FALSE FALSE FALSE FALSE
r2 FALSE FALSE FALSE  TRUE
r3  TRUE  TRUE  TRUE  TRUE
r4  TRUE  TRUE  TRUE  TRUE
r5  TRUE  TRUE  TRUE  TRUE
r6  TRUE  TRUE  TRUE  TRUE

In [46]:
df_2[df_2$c2 > 15,]

c1 c2 c3 c4
r5 16 17 18 19
r6 20 21 22 23

In [47]:
df_2[df_2$c2 > 15 | df_2$c2 == 1, ]

c1 c2 c3 c4
r1  0  1  2  3
r5 16 17 18 19
r6 20 21 22 23

In [48]:
new_row_labels <- c("r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8")
df_3 <- df_2[new_row_labels, ]
rownames(df_3) <- new_row_labels
df_3

c1 c2 c3 c4
r1  0  1  2  3
r2  4  5  6  7
r3  8  9 10 11
r4 12 13 14 15
r5 16 17 18 19
r6 20 21 22 23
r7 NA NA NA NA
r8 NA NA NA NA

In [49]:
list_1 <- list("s1"=c(1, 4, 9), "s2"=c(2, 5, 8), "s3"=c(3, 6, 7))
list_1

$s1
[1] 1 4 9

$s2
[1] 2 5 8

$s3
[1] 3 6 7

In [50]:
df_4 <- as.data.frame(list_1)
rownames(df_4) <- c("r1", "r2", "r3")
df_4

s1 s2 s3
r1 1  2  3 
r2 4  5  6 
r3 9  8  7

In [51]:
df_5 <- data.frame(
  a = c(1, 4, 9, NA),
  b = c(NA, NA, 7, NA),
  c = c(3, NA, 8, NA)
)
df_5

a  b  c 
1  1 NA  3
2  4 NA NA
3  9  7  8
4 NA NA NA

In [52]:
complete.cases(df_5)

[1] FALSE FALSE  TRUE FALSE

In [53]:
df_5[complete.cases(df_5), ]

a b c
3 9 7 8

In [54]:
is.na(df_5)

a     b     c    
[1,] FALSE  TRUE FALSE
[2,] FALSE  TRUE  TRUE
[3,] FALSE FALSE FALSE
[4,]  TRUE  TRUE  TRUE

In [55]:
colSums(is.na(df_5))

a b c 
1 3 2

In [56]:
df_5[, colSums(is.na(df_5)) == 1]

[1]  1  4  9 NA

In [57]:
df_5[rowSums(!is.na(df_5)) >= 2, ]

a b  c
1 1 NA 3
3 9  7 8

In [58]:
df_5[is.na(df_5)] <- 0
df_5

a b c
1 1 0 3
2 4 0 0
3 9 7 8
4 0 0 0

In [59]:
df_5 <- data.frame(
  a = c(1, 4, 9, NA),
  b = c(NA, NA, 7, NA),
  c = c(3, NA, 8, NA)
)

df_5$a[is.na(df_5$a)]

[1] NA

In [60]:
mean(df_5$a)
mean(df_5$a, na.rm=TRUE)

[1] NA

[1] 4.666667

In [61]:
df_5$a[is.na(df_5$a)] <- mean(df_5$a, na.rm=TRUE)
df_5

a        b  c 
1 1.000000 NA  3
2 4.000000 NA NA
3 9.000000  7  8
4 4.666667 NA NA

In [62]:
df_6 <- as.data.frame(matrix(0:15, nrow=4, ncol=4))
rownames(df_6) <- c("a_1", "a_2", "b_1", "b_2")
colnames(df_6) <- c("A_1", "A_2", "B_1", "B_2")
df_6

A_1 A_2 B_1 B_2
a_1 0   4    8  12 
a_2 1   5    9  13 
b_1 2   6   10  14 
b_2 3   7   11  15

In [63]:
grep("^a", c("c","a","b","a"))

[1] 2 4

In [64]:
grep("^a", rownames(df_6))

[1] 1 2

In [65]:
df_6[grep("^a", rownames(df_6)), ]

A_1 A_2 B_1 B_2
a_1 0   4   8   12 
a_2 1   5   9   13

## List 2

In [66]:
list_2 <- list(3, 19, 112, 4731)
list_2

[[1]]
[1] 3

[[2]]
[1] 19

[[3]]
[1] 112

[[4]]
[1] 4731

In [67]:
names(list_2) <- c("A", "B", "C", "D")
list_2

$A
[1] 3

$B
[1] 19

$C
[1] 112

$D
[1] 4731

In [68]:
list_2[[1]]
list_2$A

[1] 3

[1] 3

In [69]:
list_3 <- list(vec_1,matrix_1,df_1,list_1)
list_3

[[1]]
     1      2      3      4      5      6 
   3.0   19.0   56.0 2365.5    3.0   19.0 

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
  V1 V2 V3
1  1  4  7
2  2  5  8
3  3  6  9
4  1  2  3
5  4  5  6
6  7  8  9

[[4]]
[[4]]$s1
[1] 1 4 9

[[4]]$s2
[1] 2 5 8

[[4]]$s3
[1] 3 6 7

In [70]:
list_3[[2]]

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [71]:
list_3[[2]][,1]

[1] 1 2 3

In [72]:
list_3[[3]][3,2]

[1] 6

In [73]:
list_3[[4]]$D

NULL